//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi_AppMain.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=77.68.57.154;Initial Catalog=ElephantCar;User ID=ec;Password=ec")]
        public string ElephantCarConnectionString {
            get {
                return ((string)(this["ElephantCarConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=77.68.57.154;Initial Catalog=PDA;User ID=pda;Password=pda;Connect Tim" +
            "eout=0")]
        public string PDAConnectionString {
            get {
                return ((string)(this["PDAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=77.68.57.154;Initial Catalog=OnlineTaxiQuickBooking;Persist Security " +
            "Info=True;User ID=online;Password=online")]
        public string OnlineTaxiQuickBookingConnectionString {
            get {
                return ((string)(this["OnlineTaxiQuickBookingConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DANISH;Initial Catalog=Taxi;Integrated Security=True")]
        public string TaxiConnectionString {
            get {
                return ((string)(this["TaxiConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=213.171.197.98;Initial Catalog=PDA;User ID=pda;Password=pda")]
        public string PDAConnectionString1 {
            get {
                return ((string)(this["PDAConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=213.171.197.98;Initial Catalog=OnlineTaxiQuickBooking;User ID=online;" +
            "Password=online")]
        public string OnlineTaxiQuickBookingConnectionString1 {
            get {
                return ((string)(this["OnlineTaxiQuickBookingConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=213.171.197.98,58416;Initial Catalog=OnlineTaxiQuickBooking;User ID=o" +
            "nline;Password=online")]
        public string OnlineTaxiQuickBookingConnectionString2 {
            get {
                return ((string)(this["OnlineTaxiQuickBookingConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=88.208.245.219,58526;Initial Catalog=SysGenSetting789CommandTab;User " +
            "ID=AB125/!#^DnymaicPoliTabExpCondition;Password=85&^%TabPassPolicyExCond")]
        public string SysGenSetting789CommandTabConnectionString {
            get {
                return ((string)(this["SysGenSetting789CommandTabConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=213.171.197.98,58417;Initial Catalog=onlineWebVehicleManagementSystem" +
            ";User ID=Dur2cz31ey4;Password=Ob5ra1c3eJefzu7r4&*^")]
        public string onlineWebVehicleManagementSystemConnectionString {
            get {
                return ((string)(this["onlineWebVehicleManagementSystemConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=Taxi;Integrated Security=True")]
        public string TaxiConnectionString1 {
            get {
                return ((string)(this["TaxiConnectionString1"]));
            }
        }
    }
}
